### ISSUE TITLE
The package named node-fetch doesn't get installed with npm i, even after all the requirements are being met test files are demanding this package to be installed in order to fully pass them.

### ISSUE THREAD

**Issue by arsahindev** [learn-co-curriculum/react-hooks-redux-thunk-lab#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.

https://my.learn.co/courses/145/assignments/7834?module_item_id=17740

## Describe the bug

Write a clear and concise description of what the bug is. Include the file and
line number(s) if possible.

There's no bug, there's a package missing for the test files.

## What is the expected behavior?

Write a clear and concise description of what you expected to happen.

No problem in the behavior, tests work great but even after all the requirements are being met the files are demanding a package called node-fetch and if it doesn't get installed by the student, tests are not passing. I think this is a package that escaped from the eyes and probably should be installed with "npm install" command.

## Screenshots

If applicable, attach screenshots to help explain your problem.

Unfortunately, because I passed the problem and realised that test files demans a package named node-fetch I installed it and forgot to get a screenshot adn now cannot revert to that version to take a screenshot.

## What OS are you using?

- [ ] OS X
- [ ] WSL
- [X] Linux

## Any additional context?

Nope, I don't have anything to add but I think it is just a missing package. There's no bugs in the test files, whenever the student install tha package everything is back to normal, everything is working fine.

**Comment by graciemcguire** [comment]
Thanks for flagging, @ARS-coding! We've updated the dependencies for this lab.
